-- 000003_data_seed_characters.up.sql
-- M33-02(S02b): characters(custom_states 列を含む)。
-- ★層 B。characters / custom_states は GAME_TABLES に在る。
--
-- ★★sqlite_sequence: 行 31 / 最大 id 34。
--   旧系列では 000009(aki/jamie/guile の旧 seed)が id を 3 つ消費し、000017 が全行を削除した。
--   ⇒ 行は消えても消費済み id は戻らない。本群は id を明示投入するため、
--     AUTOINCREMENT の seq は最大 id と同じ 34 に落ち着く(M33-01 §2.6 の差 3 がこれで再現される)。
--   ★「廃止できる」と「書かなくてよい」は別である ⇒ 000009 は書かないが、その跡は id に残す。
-- ★層 B(CC-BY-SA-4.0)。SF6 の事実であり GAME_TABLES へ書くため `_data_` を持つ。

INSERT INTO characters (id, game_id, code, name_ja, name_en, custom_states) VALUES
  (1, 1, 'ryu', 'リュウ', 'Ryu', '{"states":[{"code":"denjin_charge","name_ja":"電刃錬気","name_en":"Denjin Charge","subject":"self","type":"flag","value_definition":{"kind":"boolean"},"scope":"persistent"}]}'),
  (5, 1, 'ken', 'ケン', 'Ken', NULL),
  (6, 1, 'ingrid', 'イングリッド', 'Ingrid', '{"states":[{"code":"sun_crest","name_ja":"サンシンボル","name_en":"Sun Crest","subject":"self","type":"level","value_definition":{"kind":"integer","min":0,"max":4},"show_delta":true},{"code":"order_of_the_sun","name_ja":"サンオーダー発動中","name_en":"Order of the Sun","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"level","value_definition":{"kind":"integer","min":0,"max":3,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"Lv1","label_en":"Lv1"},{"value":2,"label_ja":"Lv2","label_en":"Lv2"},{"value":3,"label_ja":"Lv3","label_en":"Lv3"}]}},{"code":"order_of_the_sun_strength","name_ja":"サンオーダーの強度","name_en":"Order of the Sun strength","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"level","value_definition":{"kind":"integer","min":0,"max":3,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"弱","label_en":"Light"},{"value":2,"label_ja":"中","label_en":"Medium"},{"value":3,"label_ja":"強","label_en":"Heavy"}]}}]}'),
  (7, 1, 'c_viper', 'C.ヴァイパー', 'C.Viper', '{"states":[{"code":"limit_decoupler","name_ja":"バウンサーステップ(SA1強化中)","name_en":"Limit Decoupler (install SA1)","subject":"self","type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (8, 1, 'dhalsim', 'ダルシム', 'Dhalsim', '{"states":[{"code":"yoga_arch_is_set","name_ja":"ヨガアーチ設置","name_en":"Yoga Arch is set","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":4,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"弱","label_en":"Light"},{"value":2,"label_ja":"中","label_en":"Medium"},{"value":3,"label_ja":"強","label_en":"Heavy"},{"value":4,"label_ja":"OD","label_en":"OD"}]}},{"code":"yoga_sunburst_is_set","name_ja":"ヨガサンバースト設置","name_en":"Yoga Sunburst is set","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":3,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"通常","label_en":"Normal"},{"value":2,"label_ja":"ホールド","label_en":"Hold"},{"value":3,"label_ja":"最大ホールド","label_en":"Max Hold"}]}},{"code":"yoga_sunburst_strength","name_ja":"ヨガサンバーストの強度","name_en":"Yoga Sunburst strength","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":3,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"弱","label_en":"Light"},{"value":2,"label_ja":"中","label_en":"Medium"},{"value":3,"label_ja":"強","label_en":"Heavy"}]}}]}'),
  (9, 1, 'terry', 'テリー', 'Terry', NULL),
  (10, 1, 'guile', 'ガイル', 'Guile', '{"states":[{"code":"solid_puncher","name_ja":"ソリッドパンチャー","name_en":"Solid Puncher","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (11, 1, 'lily', 'リリー', 'Lily', '{"states":[{"code":"windclad","name_ja":"風纏い","name_en":"Windclad","subject":"self","scope":"persistent","type":"stock","value_definition":{"kind":"integer","min":0,"max":3},"show_delta":true}]}'),
  (12, 1, 'kimberly', 'キンバリー', 'Kimberly', '{"states":[{"code":"shuriken_bomb_stock","name_ja":"手裏剣ストック","name_en":"Shuriken Bomb Stocks","subject":"self","scope":"persistent","type":"stock","value_definition":{"kind":"integer","min":0,"max":3},"show_delta":true},{"code":"shuriken_bomb_is_set","name_ja":"細工手裏剣設置数","name_en":"Shuriken Bombs Set","subject":"self","scope":"persistent","type":"stock","value_definition":{"kind":"integer","min":0,"max":3,"single_value":true}}]}'),
  (13, 1, 'juri', 'ジュリ', 'Juri', '{"states":[{"code":"fuha_stock","name_ja":"風破ストック","name_en":"Fuha Stocks","subject":"self","scope":"persistent","type":"stock","value_definition":{"kind":"integer","min":0,"max":3},"show_delta":true},{"code":"feng_shui_engine","name_ja":"風水エンジン","name_en":"Feng Shui Engine","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"flag","value_definition":{"kind":"boolean"}},{"code":"saihasho_is_set","name_ja":"歳破衝設置","name_en":"Saihasho is set","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":2,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"風破版","label_en":"Fuha"},{"value":2,"label_ja":"OD","label_en":"OD"}]}}]}'),
  (14, 1, 'mai', '舞', 'Mai', '{"states":[{"code":"flame_stock","name_ja":"焔ストック","name_en":"Flame Stock","subject":"self","scope":"persistent","type":"stock","value_definition":{"kind":"integer","min":0,"max":5},"show_delta":true},{"code":"kachousen","name_ja":"花蝶扇バウンド中","name_en":"Kachousen bouncing","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":5,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"ホールド弱","label_en":"Hold Light"},{"value":2,"label_ja":"ホールド中","label_en":"Hold Medium"},{"value":3,"label_ja":"ホールド強","label_en":"Hold Heavy"},{"value":4,"label_ja":"ホールドOD","label_en":"Hold OD"},{"value":5,"label_ja":"乱れ花蝶扇","label_en":"Midare Kachousen"}]}},{"code":"flame_kachousen","name_ja":"焔花蝶扇バウンド中","name_en":"Flame Kachousen bouncing","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":5,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"ホールド弱","label_en":"Hold Light"},{"value":2,"label_ja":"ホールド中","label_en":"Hold Medium"},{"value":3,"label_ja":"ホールド強","label_en":"Hold Heavy"},{"value":4,"label_ja":"ホールドOD","label_en":"Hold OD"},{"value":5,"label_ja":"乱れ花蝶扇","label_en":"Midare Kachousen"}]}}]}'),
  (15, 1, 'zangief', 'ザンギエフ', 'Zangief', NULL),
  (16, 1, 'manon', 'マノン', 'Manon', NULL),
  (17, 1, 'm_bison', 'ベガ', 'M. Bison', '{"states":[{"code":"psycho_mine_is_set","name_ja":"サイコマイン付与","name_en":"Psycho Mine is set","subject":"opponent","scope":"persistent","type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (18, 1, 'rashid', 'ラシード', 'Rashid', '{"states":[{"code":"ysaar","name_ja":"イウサール発動中","name_en":"Ysaar","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (19, 1, 'jamie', 'ジェイミー', 'Jamie', '{"states":[{"code":"drink_level","name_ja":"酔いレベル","name_en":"Drink Level","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":4}},{"code":"the_devils_song","name_ja":"絶唱魔身","name_en":"The Devil''s Song","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (20, 1, 'luke', 'ルーク', 'Luke', NULL),
  (21, 1, 'marisa', 'マリーザ', 'Marisa', NULL),
  (22, 1, 'jp', 'JP', 'JP', '{"states":[{"code":"departure_is_set","name_ja":"ヴィーハト設置","name_en":"Departure is set","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":4,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"弱","label_en":"Light"},{"value":2,"label_ja":"中","label_en":"Medium"},{"value":3,"label_ja":"強","label_en":"Heavy"},{"value":4,"label_ja":"OD","label_en":"OD"}]}},{"code":"lovushka","name_ja":"ラヴーシュカ発動中","name_en":"Lovushka","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (23, 1, 'aki', 'AKI', 'A.K.I.', '{"states":[{"code":"poisoned","name_ja":"毒状態","name_en":"Poisoned","subject":"opponent","scope":"persistent","type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (24, 1, 'akuma', '豪鬼', 'Akuma', NULL),
  (25, 1, 'alex', 'アレックス', 'Alex', NULL),
  (26, 1, 'blanka', 'ブランカ', 'Blanka', '{"states":[{"code":"blanka_chan_bomb","name_ja":"ブランカちゃん人形","name_en":"Blanka-chan Bomb","subject":"self","scope":"persistent","type":"stock","value_definition":{"kind":"integer","min":0,"max":3},"show_delta":true},{"code":"lightning_beast","name_ja":"ライトニングビースト","name_en":"Lightning Beast","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"flag","value_definition":{"kind":"boolean"}},{"code":"blanka_chan_bomb_is_set","name_ja":"ブランカちゃん人形設置","name_en":"Blanka-chan Bomb is set","subject":"self","scope":"persistent","type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (27, 1, 'cammy', 'キャミィ', 'Cammy', NULL),
  (28, 1, 'chun_li', '春麗', 'Chun-Li', NULL),
  (29, 1, 'dee_jay', 'ディージェイ', 'Dee Jay', NULL),
  (30, 1, 'e_honda', 'E.本田', 'E.Honda', '{"states":[{"code":"sumo_spirit","name_ja":"肩屋入り","name_en":"Sumo Spirit","subject":"self","scope":"persistent","type":"flag","value_definition":{"kind":"boolean"}}]}'),
  (31, 1, 'ed', 'エド', 'Ed', NULL),
  (32, 1, 'elena', 'エレナ', 'Elena', NULL),
  (33, 1, 'sagat', 'サガット', 'Sagat', NULL),
  (34, 1, 'yasmine', 'ヤスミン', 'Yasmine', '{"states":[{"code":"bayani_mode","name_ja":"バヤニモード","name_en":"Bayani Mode","subject":"self","scope":"persistent","type":"flag","value_definition":{"kind":"boolean"}},{"code":"nakatagong_lakas","name_ja":"ナカタゴン・ラカス","name_en":"Nakatagong Lakas","subject":"self","scope":"conditional","activation":{"trigger":"sa2_active"},"type":"flag","value_definition":{"kind":"boolean"}},{"code":"pangil_sa_likuran_is_set","name_ja":"パンギル・サ・リクラン設置","name_en":"Pangil sa Likuran is set","subject":"self","scope":"persistent","type":"level","value_definition":{"kind":"integer","min":0,"max":6,"single_value":true,"options":[{"value":0,"label_ja":"なし","label_en":"None"},{"value":1,"label_ja":"弱","label_en":"Light"},{"value":2,"label_ja":"中","label_en":"Medium"},{"value":3,"label_ja":"強","label_en":"Heavy"},{"value":4,"label_ja":"OD弱","label_en":"OD Light"},{"value":5,"label_ja":"OD中","label_en":"OD Medium"},{"value":6,"label_ja":"OD強","label_en":"OD Heavy"}]}}]}');
