// Package desktop is the app's thin desktop-integration layer (M34):
// notification-area (tray) residency, native confirm/alert dialogs, and
// "open this in the user's browser / file manager".
//
// Why it exists: the app runs in a visible console window and is stopped by
// closing that window — which reads as "a developer thing" to a general user,
// and closing it by mistake kills the app. The Windows exe will therefore be
// built for the GUI subsystem (no console at all, M34-02) and this package
// provides what the console used to provide — a visible sign that the app is
// running, and a deliberate way to stop it.
//
// Design constraints (CLAUDE.md §6 = 依存ポリシー):
//   - go.mod に依存を足さない(ライセンス面の安全側)。Win32 は syscall.NewLazyDLL で
//     直接叩く。★M34-02 段 6 でブラウザ起動だけは既存の direct 依存
//     github.com/pkg/browser(BSD-2-Clause)へ委譲した ——
//     本体は元からそれを持っており、新規依存は 0 件のままである(go.mod / go.sum 無変更)。
//   - OS 依存は desktop_windows.go / desktop_other.go に閉じ込め、この
//     ファイルは純粋関数とプラットフォーム非依存の API だけを持つ(テスト可能)。
//   - 実装は Windows のみ。他 OS ではトレイは ErrUnsupported を返し、
//     アラートは stderr に落ちる(開発機が Linux/macOS でも動くように)。
//
// 移植元: 開発者本人の非公開リポジトリ autopilot-combomgr の
// projects/moves-input-tool/internal/desktop(M34-01 で移植)。第三者由来の断片は
// 無いことを実査済みで、出所と根拠は docs/progress/progress-log.md が正本。
// ライセンスは REUSE.toml の既定(層 A = AGPL-3.0-or-later)で解決される。
package desktop

import (
	_ "embed"
	"encoding/binary"
	"errors"
	"fmt"
	"net/url"
	"os"
	"runtime"

	"github.com/pkg/browser"
)

// iconICO is the notification-area icon, regenerated by
// `go run ./cmd/genicon > internal/desktop/icon.ico` (self-authored, so no
// third-party asset licence is involved — CLAUDE.md ★).
//
//go:embed icon.ico
var iconICO []byte

// ErrUnsupported is returned by RunTray on platforms without an implementation.
// Callers must treat it as "keep running without a tray icon", never as fatal —
// the browser UI still has a stop button.
var ErrUnsupported = errors.New("この OS では常駐アイコンに対応していません")

// TrayMenu describes the notification-area icon and its right-click menu.
// Every callback runs on the tray's own thread; keep them short and hand real
// work to another goroutine.
type TrayMenu struct {
	Title   string // menu header / dialog caption
	Tooltip string // hover text — this is the "is it running?" indicator
	Items   []TrayItem
}

// TrayItem is one right-click menu entry. Default marks the entry that also
// runs on a left double-click of the icon.
type TrayItem struct {
	Label   string
	OnClick func()
	Default bool
}

// ValidateURL rejects anything that is not a plain http/https URL, so a URL
// built from config (host / port) can never turn into an arbitrary
// shell/protocol invocation.
func ValidateURL(raw string) error {
	u, err := url.Parse(raw)
	if err != nil {
		return fmt.Errorf("URL を解釈できません: %w", err)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return fmt.Errorf("http/https 以外の URL は開きません: %q", raw)
	}
	if u.Host == "" {
		return fmt.Errorf("ホストの無い URL は開きません: %q", raw)
	}
	return nil
}

// launchCmd is a helper process to start, plus how to show it.
type launchCmd struct {
	Name string
	Args []string
	// HideWindow は「ヘルパ自身のウィンドウを隠すか」。
	//
	//	true  — 「対象を起動して即座に消えるだけ」のヘルパ。隠さないと一瞬ウィンドウが
	//	        出て、M34 で消したはずの黒窓が復活する。
	//	false — explorer のように「そのウィンドウこそが目的」のプロセス。
	//	        隠すとプロセスは起動するのに画面には何も出ず、Start() も成功するので
	//	        エラーにすらならない(2026-08-04 の実機検証で踏んだ不具合)。
	//
	// ★★現在 true を立てる呼び手は無い(M34-02 段 6 でブラウザ起動を pkg/browser へ
	// 委譲したため。それまでは rundll32 が true だった)。⇒ フィールドを残してあるのは、
	// 「explorer を隠してはならない」という上記の実機知見をこの false が型で保っている
	// からである(回帰テスト TestFolderCommandNeverHidesWindow が対応する)。
	HideWindow bool
}

// folderCommand builds the "reveal this directory" command for a GOOS.
func folderCommand(goos, dir string) (launchCmd, error) {
	if dir == "" {
		return launchCmd{}, errors.New("フォルダのパスが空です")
	}
	switch goos {
	case "windows":
		// explorer のウィンドウを見せるのが目的なので、絶対に隠さない。
		return launchCmd{"explorer.exe", []string{dir}, false}, nil
	case "darwin":
		return launchCmd{"open", []string{dir}, false}, nil
	default:
		return launchCmd{"xdg-open", []string{dir}, false}, nil
	}
}

// iconImage extracts the first image's raw bytes from an .ico file.
//
// CreateIconFromResourceEx wants the image payload (BITMAPINFOHEADER + pixels),
// not the ICONDIR/ICONDIRENTRY header that prefixes a file on disk — so the
// directory entry is parsed to find where the payload starts. Kept here rather
// than in the Windows file so it can be tested on any platform.
func iconImage(ico []byte) ([]byte, error) {
	const (
		dirSize   = 6  // ICONDIR: reserved(2) type(2) count(2)
		entrySize = 16 // ICONDIRENTRY
	)
	if len(ico) < dirSize+entrySize {
		return nil, errors.New("ico が短すぎます")
	}
	if binary.LittleEndian.Uint16(ico[0:2]) != 0 || binary.LittleEndian.Uint16(ico[2:4]) != 1 {
		return nil, errors.New("ico のヘッダが不正です")
	}
	if binary.LittleEndian.Uint16(ico[4:6]) == 0 {
		return nil, errors.New("ico に画像が入っていません")
	}
	size := binary.LittleEndian.Uint32(ico[dirSize+8 : dirSize+12])
	off := binary.LittleEndian.Uint32(ico[dirSize+12 : dirSize+16])
	end := uint64(off) + uint64(size)
	if size == 0 || end > uint64(len(ico)) {
		return nil, fmt.Errorf("ico の画像位置が不正です (offset=%d size=%d len=%d)", off, size, len(ico))
	}
	return ico[off:end], nil
}

// OpenURL launches the user's default browser.
//
// ★★いつ返るかは OS で違う。⇒ 「すぐ返る」を前提にしないこと ————————————
// 委譲前(自前の spawn = exec.Command(...).Start())は常にすぐ返っていたが、
// pkg/browser の実装は次のとおりである(実測 v0.0.0-20240102092130-5ac0b6a4141c)。
//
//	Windows      — windows.ShellExecute。子プロセスを spawn せず、すぐ返る。
//	Linux/macOS  — xdg-open / open を exec.Command(...).Run() で起動するため、
//	               そのヘルパが終わるまで返らない。
//
// ⇒ 本体の呼び手 3 つのうち、トレイのメニュー(desktop.invoke が go で回す)と
// launchBrowser(自前の goroutine)は待たない形になっている。二重起動の判別
// (openExistingInstance)だけは同期で呼ぶ —— そのまま退くプロセスであり、
// 開けたかどうかを知る必要があるためである。
//
// ★★実際の起動は github.com/pkg/browser へ委譲する(M34-02 段 6 / followup
// `browser-launch-duplication`) ————————————————————————————————————————————
// 移植直後は rundll32 を自前で叩いていた。移植元のコメントは「cmd /c start だと黒窓が
// 一瞬出る」を理由に自前実装を選んでいたが、その理由は本体では成立しない ——
// pkg/browser の Windows 実装は ShellExecute であって黒窓を出さないし、同モジュールは
// 元から go.mod の direct 依存である(移植元は外部依存 0 本のリポジトリだった)。
// ⇒ 経路を 2 本持つと CLAUDE.md §6「重複機能ライブラリは導入しない」の趣旨から外れる。
//
// ★★ValidateURL は捨てない —— 設定由来の文字列が任意のプロトコル起動に化けるのを
// 防ぐ唯一の関門である。⇒ 委譲する前に必ず通す。
func OpenURL(raw string) error {
	if err := ValidateURL(raw); err != nil {
		return err
	}
	return browser.OpenURL(raw)
}

// OpenFolder shows dir in the platform file manager (tray menu convenience:
// that is where the log file and the DB land — M34-overview §5.1.6 の
// 「ログフォルダを開く」と「DB のフォルダを開く」がこれを使う).
//
// The directory is stat'd first: the file manager is started and never waited
// on, so a bad path would otherwise fail silently — "選んでも何も起きない" with
// nothing in the log to explain it.
func OpenFolder(dir string) error {
	c, err := folderCommand(runtime.GOOS, dir)
	if err != nil {
		return err
	}
	fi, err := os.Stat(dir)
	if err != nil {
		return fmt.Errorf("フォルダを確認できません(%s): %w", dir, err)
	}
	if !fi.IsDir() {
		return fmt.Errorf("フォルダではありません: %s", dir)
	}
	return spawn(c)
}
